"""empty message

Revision ID: 1598d33a1ca2
Revises: 5905f0769f50
Create Date: 2023-12-24 01:03:13.599082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1598d33a1ca2'
down_revision = '5905f0769f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
